---
version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: majavapaja/majavashakki-ci
      - image: mongo:3.2.21-jessie
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - npm-package-cache-{{ checksum "package-lock.json" }}
      - run: ./.circleci/circleci.sh
      - save_cache:
          key: npm-package-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
