---
version: 2

jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: majavapaja/majavashakki-ci
      - image: mongo:3.2.21-jessie
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - server-node_modules-cache-{{ checksum "package-lock.json" }}
            - deployment-node_modules-cache-{{ checksum "deployment/package-lock.json" }}
      - run: ./.circleci/circleci.sh
      - save_cache:
          key: server-node_modules-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: deployment-node_modules-cache-{{ checksum "deployment/package-lock.json" }}
          paths:
            - ./deployment/node_modules
