# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |v|
    v.name = "majavashakki-dev"
  end

  config.vm.network "forwarded_port", guest: 27017, host: 27017

  config.vm.provision "ansible_local" do |ansible|
    ansible.provisioning_path = "/vagrant"
    ansible.playbook = "local-services.yml"
    ansible.verbose = "-vvv"
  end
end
