version: "3"
services:
  majavashakki-mongo:
    image: mongo
    restart: always
    volumes:
      - majavashakki-data:/data/db
    ports:
      - 27017:27017

  majavashakki-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: majavashakki-mongo
volumes:
  majavashakki-data: