name: Docker Hub Build and Push

on:
  schedule:
  - cron: "0 12 * * 0-6"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: docker login
      run: docker login -u majavashakkiservice -p ${{secrets.DOCKERHUB_PASSWORD}}
    - name: docker build
      run: docker build -t majavapaja/majavashakki:latest .
    - name: docker push
      run: docker push majavapaja/majavashakki:latest
