name: Test & Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Start MongoDB As Docker
      uses: wbari/start-mongoDB@v0.2
    - name: Install packages
      run: npm ci
    - name: Run lint
      run: npm run lint
    - name: Run tests
      run: TS_NODE_FILES=true npm run test
    - name: Run browser tests
      run: TS_NODE_FILES=true npm run test:browser
    - name: Build
      run: npm run build
