name: Test & Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
    - name: Start MongoDB As Docker
      run: docker run --name mongo -d -p 27017:27017 mongo:latest
    - name: Install packages
      run: npm ci
    - name: Run lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Run tests
      env:
        TS_NODE_FILES: true
      run: npm run test
    - name: Run browser tests
      env:
        TS_NODE_FILES: true
        CI: true
        TEST_PORT: 3002
        DEBUG: "puppeteer:*"
      run: npm run test:browser
