name: Test Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Start MongoDB As Docker
      run: docker run --name mongo -d -p 27017:27017 mongo:latest
    - name: Install packages
      run: npm ci
      env:
        PUPPETEER_SKIP_DOWNLOAD: true
    - name: Run lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Run tests
      env:
        TS_NODE_FILES: true
      run: npm run test
    - name: Run browser tests
      env:
        TS_NODE_FILES: true
        CI: true
      run: PUPPETEER_EXECUTABLE_PATH="$( which chromium-browser )" npm run test:browser
